// Card descriptions
const String desc1 =
    "Tap here to learn about what climate change is, how it was discovered and the global efforts today!";
const String desc2 =
    "Tap here to learn about the various effects of climate change on our planet, and how it threatens our future!";
const String desc3 =
    "Tap here to learn how to do your part in this global fight, and ensure a safe future for everyone!";

// Page 1
const String climateHistory =
    "The history of the scientific discovery of climate change began in the early 19th century when ice ages and other natural changes in paleoclimate were first suspected and the natural greenhouse effect was first identified. In the late 19th century, scientists first argued that human emissions of greenhouse gases could change Earth's energy balance and climate. Many other theories of climate change were advanced, involving forces from volcanism to solar variation. In the 1960s, the evidence for the warming effect of carbon dioxide gas became increasingly convincing.\n\nIn the 1980s, the terms global warming and climate change became more common. Though the two terms are sometimes used interchangeably, scientifically, global warming refers only to increased surface warming, while climate change describes the totality of changes to Earth's climate system. Global warming—used as early as 1975—became the more popular term after NASA climate scientist James Hansen used it in his 1988 testimony in the U.S. Senate. Since the 2000s, climate change has increased in usage. Climate change can also refer more broadly to both human-caused changes or natural changes throughout Earth's history.";
const String climateIgnorance =
    "Humans have ignored climate change for a number of reasons. Some people simply do not believe that climate change is real or that it is caused by human activities. Others may believe that the effects of climate change are still far in the future and that there is plenty of time to take action. Still others may feel that the cost of reducing greenhouse gas emissions is too high, or that it is a problem that can only be solved by governments and businesses.\n\nWhatever the reason, human inaction on climate change is a serious problem. The evidence for climate change is overwhelming, and the impacts of climate change are already being felt around the world. We need to take urgent action to reduce greenhouse gas emissions and mitigate the effects of climate change.";
const String climatePresent =
    "The Earth's climate is changing at an unprecedented rate. The average global temperature has increased by about 1 degree Celsius since the pre-industrial era, and the rate of warming is accelerating. This warming is causing a number of changes to the Earth's climate system, including rising sea levels, more extreme weather events, and changes in precipitation patterns.\n\nThe effects of climate change are already being felt around the world. In some places, climate change is causing more frequent and severe droughts, while in others it is causing more flooding. Climate change is also causing more extreme heat waves and cold snaps, as well as more intense hurricanes and cyclones. These changes are having a significant impact on human health, agriculture, and infrastructure.";

// Page 2
const String climateEffects =
    "Rising sea levels: Rising sea levels are threatening coastal communities and infrastructure around the world. In some places, sea levels have risen by more than 2 feet in the past century. This is causing coastal flooding and erosion, and it is displacing millions of people.\n\nMore extreme weather events: Climate change is causing more extreme weather events, such as heat waves, droughts, floods, and wildfires. These events are causing widespread damage and loss of life. For example, the 2017 Hurricane Harvey caused an estimated \$125 billion in damage in the United States.\n\nChanges in precipitation patterns: Climate change is causing changes in precipitation patterns. In some places, this is leading to more droughts, while in other places it is leading to more flooding. This is making it difficult to predict crop yields and water supplies.\n\nMelting glaciers: Glaciers around the world are melting at an alarming rate. This is causing water shortages in many parts of the world, and it is contributing to sea level rise.\n\nLoss of plant and animal life: Climate change is causing many plant and animal species to move to new areas in search of cooler temperatures and more suitable habitats. Some species are unable to adapt to the changing climate and are becoming extinct.\n\nThe harmful effects of climate change are only going to get worse if we do not take action to reduce greenhouse gas emissions. We need to make a transition to a clean energy economy, and we need to invest in adaptation measures to help communities cope with the effects of climate change. We can still avert the worst impacts of climate change, but we need to act now.";

// Page 3
const String climateAction =
    "Reduce your energy consumption. This can be done by making small changes in your daily life, such as turning off lights when you leave a room, unplugging appliances when they are not in use, and weatherizing your home.\n\nDrive less. If you can, walk, bike, or take public transportation instead of driving. If you do need to drive, carpool or take a bus or train.\n\nEat less meat. Producing meat requires a lot of energy and water, and it also produces greenhouse gases. Eating less meat can help reduce your carbon footprint.\n\nRecycle and compost. Recycling and composting help to reduce the amount of waste that goes to landfills. Landfills produce methane, a greenhouse gas that is even more potent than carbon dioxide.\n\nSupport sustainable businesses. When you shop, look for businesses that are committed to sustainability. This could include businesses that use renewable energy, recycle their waste, or donate to environmental causes.\n\nGet involved in your community. There are many ways to get involved in your community to help fight climate change. You can volunteer for an environmental organization, attend city council meetings, or write to your elected officials about climate change.\n\nEvery little bit helps! By making small changes in our daily lives, we can all make a difference in the fight against climate change.";
